name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: sinaprj-web
          outputs: dist/github-contribution-grid-snake-dark.svg

      - name: Commit and Push Snake to main branch
        run: |
          mkdir -p dist
          cp dist/github-contribution-grid-snake-dark.svg .
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake-dark.svg
          git commit -m "Update snake animation [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
